"""removed phone_number column from posts table

Revision ID: eaaf222e4654
Revises: df77dc9f1fd4
Create Date: 2025-06-02 00:20:59.033730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaaf222e4654'
down_revision: Union[str, None] = 'df77dc9f1fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
